import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Heading from '../components/Heading'

export default function Home() {
	return (
		<div className={styles.wrapper}>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Heading text="Hello world!" />
		</div>
	)
}
